//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sudoku1.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudoku
    {
        public int SudokuId { get; set; }
        public byte[] SudokuArray { get; set; }
        public System.DateTime SudokuDate { get; set; }
        public bool IsLoaded { get; set; }
    }
}
